"""Canada location data for the /canada/ pages (provinces/territories + cities).

PROVINCES: slug, name, abbr, capital, time zone, common home-internet providers, French-language hint, local note.
CITIES: province slug, city, slug, teams, nearby, local note, optional extra intro HTML (kept from the
original city pages), station match words (looked up in the CANADA group of src/data/channels.json).
"""

PROVINCES = [
    ("ontario", "Ontario", "ON", "Toronto", "Eastern", "Bell, Rogers, Cogeco and TekSavvy", "Ontario is home to Canada’s biggest TV market — and hockey night is still the biggest night of the week."),
    ("quebec", "Quebec", "QC", "Quebec City", "Eastern", "Vidéotron, Bell, Cogeco and Fizz", "Quebec households want French channels first — TVA, ICI Radio-Canada, Noovo, RDS and TVA Sports — with English networks alongside."),
    ("british-columbia", "British Columbia", "BC", "Victoria", "Pacific", "Telus, Rogers (formerly Shaw) and Novus", "On Pacific time, many national broadcasts and East Coast games start in the afternoon, so catch-up and recording come in handy."),
    ("alberta", "Alberta", "AB", "Edmonton", "Mountain", "Telus and Rogers (formerly Shaw)", "The Battle of Alberta between the Oilers and Flames is one of the most-watched rivalries in Canadian sport."),
    ("manitoba", "Manitoba", "MB", "Winnipeg", "Central", "Bell MTS and Rogers (formerly Shaw)", "Manitoba’s long winters and loyal Jets and Blue Bombers fans make TV a year-round habit."),
    ("saskatchewan", "Saskatchewan", "SK", "Regina", "Central (no DST)", "SaskTel, Access Communications and Rogers", "Rider Nation stretches across the whole province — every Roughriders game is a big event."),
    ("nova-scotia", "Nova Scotia", "NS", "Halifax", "Atlantic", "Bell (Aliant) and Eastlink", "On Atlantic time, late West Coast games run past midnight — catch-up lets you watch the next morning."),
    ("new-brunswick", "New Brunswick", "NB", "Fredericton", "Atlantic", "Bell (Aliant) and Rogers", "New Brunswick is Canada’s only officially bilingual province, so households want both French and English channels."),
    ("newfoundland-and-labrador", "Newfoundland and Labrador", "NL", "St. John’s", "Newfoundland", "Bell (Aliant) and Rogers", "Newfoundland runs half an hour ahead of Atlantic time — a TV guide in your own time zone matters."),
    ("prince-edward-island", "Prince Edward Island", "PE", "Charlottetown", "Atlantic", "Bell (Aliant) and Eastlink", "PEI viewers follow the Islanders in the QMJHL and every major national broadcast."),
    ("yukon", "Yukon", "YT", "Whitehorse", "Yukon (year-round MST)", "Northwestel and Starlink", "In the North, cable options are limited — IPTV over fibre or satellite internet like Starlink is often the simplest choice."),
    ("northwest-territories", "Northwest Territories", "NT", "Yellowknife", "Mountain", "Northwestel and Starlink", "Remote communities in the NWT can use IPTV anywhere they can get internet, including Starlink."),
    ("nunavut", "Nunavut", "NU", "Iqaluit", "Eastern / Central / Mountain", "Northwestel and Starlink", "Low-earth-orbit satellite internet has made streaming practical in many Nunavut communities for the first time."),
]

TOR = ["Toronto Maple Leafs (NHL)", "Toronto Raptors (NBA)", "Toronto Blue Jays (MLB)", "Toronto FC (MLS)", "Toronto Argonauts (CFL)"]
MTL = ["Montréal Canadiens (NHL)", "CF Montréal (MLS)", "Montréal Alouettes (CFL)"]
VAN = ["Vancouver Canucks (NHL)", "Vancouver Whitecaps (MLS)", "BC Lions (CFL)"]
CGY = ["Calgary Flames (NHL)", "Calgary Stampeders (CFL)"]
EDM = ["Edmonton Oilers (NHL)", "Edmonton Elks (CFL)"]

CITIES = [
    # ------------------------------------------------------------- Ontario
    ("ontario", "Toronto", "toronto", TOR, ["Mississauga", "Brampton", "Markham", "Vaughan", "Hamilton", "Oshawa"],
     "Toronto households pay some of the highest TV bills in Canada, often $80–$120 a month for cable before sports add-ons. IPTV keeps the channels Torontonians actually watch — CP24, the Leafs, the Raptors, the Jays — and adds a huge on-demand library for a fraction of the price.",
     "<h3>Watching in a Toronto condo</h3><p>Busy building Wi-Fi can cause buffering at peak times. Use 5 GHz Wi-Fi or an Ethernet adapter for your Firestick, and place the router in the same room as the TV if you can.</p>",
     ["TORONTO", "CP24", "OMNI", "CITY TORONTO"]),
    ("ontario", "Ottawa", "ottawa", ["Ottawa Senators (NHL)", "Ottawa Redblacks (CFL)", "Atlético Ottawa (CPL)"], ["Gatineau", "Kingston", "Montreal"],
     "Ottawa–Gatineau is a bilingual region, and IPTV gives you English and French channels together: CTV Ottawa and CBC alongside TVA Gatineau, ICI Radio-Canada, RDS and TVA Sports.",
     "<h3>Both sides of the river</h3><p>IPTV works the same in Ottawa and Gatineau — see our <a href=\"/iptv-quebec/\">page en français</a>.</p>",
     ["OTTAWA", "GATINEAU"]),
    ("ontario", "Mississauga", "mississauga", TOR, ["Toronto", "Brampton", "Oakville", "Etobicoke"],
     "Mississauga is one of Canada’s most diverse cities; one subscription covers Toronto locals plus channels from Europe and beyond.", "", ["TORONTO"]),
    ("ontario", "Brampton", "brampton", ["Brampton Steelheads (OHL)"] + TOR[:3], ["Mississauga", "Toronto", "Vaughan"],
     "Brampton’s fast-growing neighbourhoods are full of new homes with fibre internet — ideal for streaming in 4K.", "", ["TORONTO"]),
    ("ontario", "Hamilton", "hamilton", ["Hamilton Tiger-Cats (CFL)", "Forge FC (CPL)", "Toronto Maple Leafs (NHL)"], ["Burlington", "Oakville", "St. Catharines", "Toronto"],
     "Hamilton sits between Toronto and Niagara, and many households watch Toronto stations and teams. Ti-Cats fans get the CFL on TSN, and soccer fans can follow Forge FC and the Premier League.", "", ["CHCH", "TORONTO"]),
    ("ontario", "London", "london", ["London Knights (OHL)", "Western Mustangs"] + TOR[:1], ["Kitchener", "Windsor", "Guelph"],
     "London is a big OHL town — and a student city where streaming has long replaced cable.", "", ["TORONTO"]),
    ("ontario", "Markham", "markham", TOR, ["Richmond Hill", "Toronto", "Vaughan", "Scarborough"],
     "Markham’s tech parks and multicultural neighbourhoods make it a natural fit for a multi-device IPTV plan.", "", ["TORONTO"]),
    ("ontario", "Vaughan", "vaughan", TOR, ["Toronto", "Brampton", "Richmond Hill", "Markham"],
     "Vaughan has a large Italian-Canadian community — Italian channels like RAI and Canale 5 are included alongside Toronto locals.", "", ["TORONTO"]),
    ("ontario", "Kitchener", "kitchener", ["Kitchener Rangers (OHL)"] + TOR[:2], ["Waterloo", "Cambridge", "Guelph", "London"],
     "Kitchener’s Rangers are one of junior hockey’s best-supported teams.", "", ["TORONTO"]),
    ("ontario", "Waterloo", "waterloo", ["Kitchener Rangers (OHL)", "Waterloo Warriors"] + TOR[:1], ["Kitchener", "Cambridge", "Guelph"],
     "Waterloo’s university and tech community were early cord-cutters.", "", ["TORONTO"]),
    ("ontario", "Cambridge", "cambridge", ["Kitchener Rangers (OHL)"] + TOR[:2], ["Kitchener", "Waterloo", "Guelph", "Hamilton"],
     "Cambridge sits between Kitchener and Hamilton and gets both Toronto and Hamilton stations.", "", ["TORONTO", "CHCH"]),
    ("ontario", "Windsor", "windsor", ["Windsor Spitfires (OHL)", "Detroit Red Wings (NHL)", "Toronto Maple Leafs (NHL)"], ["London", "Detroit"],
     "Windsor viewers can see Detroit across the river — US networks from Detroit are in the lineup along with Canadian channels.", "", ["TORONTO"]),
    ("ontario", "Richmond Hill", "richmond-hill", TOR, ["Markham", "Vaughan", "Toronto"],
     "Richmond Hill households get the full Toronto lineup plus international channels for its diverse communities.", "", ["TORONTO"]),
    ("ontario", "Oakville", "oakville", TOR, ["Burlington", "Mississauga", "Milton", "Hamilton"],
     "Oakville sits between Toronto and Hamilton and gets stations from both.", "", ["TORONTO", "CHCH"]),
    ("ontario", "Burlington", "burlington", ["Hamilton Tiger-Cats (CFL)"] + TOR[:2], ["Hamilton", "Oakville", "Milton"],
     "Burlington viewers split between Hamilton and Toronto teams and stations.", "", ["CHCH", "TORONTO"]),
    ("ontario", "Oshawa", "oshawa", ["Oshawa Generals (OHL)"] + TOR[:2], ["Whitby", "Ajax", "Pickering", "Toronto"],
     "Oshawa’s Generals are one of the OHL’s most storied clubs.", "", ["TORONTO"]),
    ("ontario", "Barrie", "barrie", ["Barrie Colts (OHL)"] + TOR[:2], ["Toronto", "Vaughan"],
     "Barrie commuters to Toronto love catch-up TV that fits their schedule.", "", ["TORONTO"]),
    ("ontario", "St. Catharines", "st-catharines", ["Toronto Maple Leafs (NHL)", "Buffalo Sabres (NHL)", "Buffalo Bills (NFL)"], ["Niagara Falls", "Hamilton", "Buffalo"],
     "In the Niagara region, Buffalo’s Bills and Sabres are as popular as Toronto’s teams.", "", ["TORONTO", "CHCH"]),
    ("ontario", "Niagara Falls", "niagara-falls", ["Buffalo Bills (NFL)", "Buffalo Sabres (NHL)", "Toronto Maple Leafs (NHL)"], ["St. Catharines", "Buffalo", "Hamilton"],
     "Niagara Falls sits right on the US border, with Buffalo teams a short drive away.", "", ["TORONTO"]),
    ("ontario", "Guelph", "guelph", ["Guelph Storm (OHL)"] + TOR[:2], ["Kitchener", "Waterloo", "Cambridge", "Hamilton"],
     "Guelph is a university city where streaming is the norm.", "", ["TORONTO"]),
    ("ontario", "Kingston", "kingston", ["Kingston Frontenacs (OHL)", "Ottawa Senators (NHL)", "Toronto Maple Leafs (NHL)"], ["Ottawa", "Oshawa"],
     "Kingston sits halfway between Toronto and Ottawa — fans of both teams live here.", "", ["TORONTO", "OTTAWA"]),
    ("ontario", "Sudbury", "sudbury", ["Sudbury Wolves (OHL)", "Toronto Maple Leafs (NHL)"], ["Thunder Bay", "Barrie"],
     "Northern Ontario viewers get national channels and both English and French networks.", "", ["ICI TELE ONTARIO"]),
    ("ontario", "Thunder Bay", "thunder-bay", ["Winnipeg Jets (NHL)", "Toronto Maple Leafs (NHL)"], ["Sudbury", "Winnipeg"],
     "Thunder Bay is closer to Winnipeg than Toronto — and it’s on Eastern time.", "", []),
    ("ontario", "Milton", "milton", TOR, ["Oakville", "Burlington", "Mississauga"],
     "Milton is one of Canada’s fastest-growing towns; new homes mean new internet and no need for cable.", "", ["TORONTO"]),
    ("ontario", "Ajax", "ajax", TOR, ["Pickering", "Whitby", "Oshawa", "Scarborough"],
     "Ajax households in Durham Region get the full Toronto lineup.", "", ["TORONTO"]),
    ("ontario", "Pickering", "pickering", TOR, ["Ajax", "Scarborough", "Whitby"],
     "Pickering commuters can catch up on games and shows whenever they get home.", "", ["TORONTO"]),
    ("ontario", "Whitby", "whitby", ["Oshawa Generals (OHL)"] + TOR[:2], ["Oshawa", "Ajax", "Pickering"],
     "Whitby fans follow the Generals next door and the Leafs in Toronto.", "", ["TORONTO"]),
    ("ontario", "Scarborough", "scarborough", TOR, ["Markham", "Pickering", "North York", "Toronto"],
     "Scarborough is one of the most multicultural communities in Canada — international channels are included with every plan.", "", ["TORONTO"]),
    ("ontario", "Etobicoke", "etobicoke", TOR, ["Mississauga", "Toronto", "North York"],
     "Etobicoke’s condos along the lake are a perfect fit for Wi-Fi-only TV setups.", "", ["TORONTO"]),
    ("ontario", "North York", "north-york", TOR, ["Toronto", "Scarborough", "Vaughan", "Etobicoke"],
     "North York’s high-rise living makes IPTV over Wi-Fi far simpler than installing cable.", "", ["TORONTO"]),
    # ------------------------------------------------------------- Quebec
    ("quebec", "Montreal", "montreal", MTL + ["Laval Rocket (AHL)"], ["Laval", "Longueuil", "Brossard", "Terrebonne"],
     "Montréal is Canada’s most bilingual TV market, and IPTV suits it perfectly: English and French channels in one lineup — TVA, ICI Radio-Canada, Noovo, RDS and TVA Sports alongside CTV, CBC, TSN and Sportsnet.",
     "<h3>Grand Prix season</h3><p>Formula 1 fans can watch the Grand Prix du Canada on TSN, RDS or Sky Sports F1 — see our <a href=\"/f1-iptv/\">F1 IPTV guide</a>.</p>",
     ["MONTREAL"]),
    ("quebec", "Quebec City", "quebec-city", ["Québec Remparts (QMJHL)", "Montréal Canadiens (NHL)"], ["Lévis", "Trois-Rivières", "Saguenay"],
     "Quebec City is overwhelmingly French-speaking — TVA Québec, ICI Radio-Canada Québec and V are all included.", "", ["QUEBEC CITY", "ICI RADIO-CANADA TELE QUEBEC", "ICI TELE QUEBEC"]),
    ("quebec", "Laval", "laval", ["Laval Rocket (AHL)"] + MTL[:1], ["Montreal", "Terrebonne", "Longueuil"],
     "Laval has its own AHL team, the Rocket, and gets the full Montréal lineup.", "", ["MONTREAL"]),
    ("quebec", "Gatineau", "gatineau", ["Gatineau Olympiques (QMJHL)", "Ottawa Senators (NHL)", "Montréal Canadiens (NHL)"], ["Ottawa", "Montreal"],
     "Gatineau viewers get both Ottawa’s English stations and French channels like TVA Gatineau.", "", ["GATINEAU", "OTTAWA"]),
    ("quebec", "Longueuil", "longueuil", MTL, ["Montreal", "Brossard", "Laval"],
     "Longueuil is just across the river from Montréal and shares all its channels and teams.", "", ["MONTREAL"]),
    ("quebec", "Sherbrooke", "sherbrooke", ["Sherbrooke Phoenix (QMJHL)", "Montréal Canadiens (NHL)"], ["Montreal", "Trois-Rivières"],
     "Sherbrooke is an Eastern Townships university city; ICI Télé Estrie is in the lineup.", "", ["ESTRIE"]),
    ("quebec", "Trois-Rivières", "trois-rivieres", ["Trois-Rivières Lions (ECHL)", "Montréal Canadiens (NHL)"], ["Quebec City", "Montreal", "Sherbrooke"],
     "Trois-Rivières sits halfway between Montréal and Quebec City; TVA Trois-Rivières and ICI Mauricie are included.", "", ["TROIS-RIVIERES", "MAURICIE"]),
    ("quebec", "Saguenay", "saguenay", ["Chicoutimi Saguenéens (QMJHL)", "Montréal Canadiens (NHL)"], ["Quebec City"],
     "Saguenay viewers get regional ICI Télé Saguenay plus every national network.", "", ["SAGUENAY"]),
    ("quebec", "Lévis", "levis", ["Québec Remparts (QMJHL)", "Montréal Canadiens (NHL)"], ["Quebec City"],
     "Lévis sits across the St. Lawrence from Quebec City and shares its stations.", "", ["QUEBEC CITY"]),
    ("quebec", "Terrebonne", "terrebonne", MTL, ["Laval", "Montreal"],
     "Terrebonne on the North Shore gets the complete Montréal lineup.", "", ["MONTREAL"]),
    ("quebec", "Brossard", "brossard", MTL, ["Longueuil", "Montreal"],
     "Brossard’s South Shore neighbourhoods get every Montréal channel and team.", "", ["MONTREAL"]),
    # ------------------------------------------------------------- British Columbia
    ("british-columbia", "Vancouver", "vancouver", VAN, ["Burnaby", "Surrey", "Richmond", "Coquitlam", "North Vancouver"],
     "In Vancouver, many live events start early: Eastern hockey games at 4 p.m. and Premier League matches at dawn. IPTV with catch-up and recording lets you watch on your schedule.",
     "<h3>Pacific time TV guide</h3><p>If the guide looks three hours off, set your app’s EPG time offset or your device’s time zone to Pacific time.</p>",
     ["VANCOUVER"]),
    ("british-columbia", "Surrey", "surrey", VAN, ["Vancouver", "Langley", "Delta", "Burnaby"],
     "Surrey is one of BC’s fastest-growing cities, with large families who need multi-device plans.", "", ["VANCOUVER"]),
    ("british-columbia", "Burnaby", "burnaby", VAN, ["Vancouver", "Coquitlam", "Richmond"],
     "Burnaby’s Metrotown high-rises make Wi-Fi-only TV setups easy.", "", ["VANCOUVER"]),
    ("british-columbia", "Richmond", "richmond-bc", VAN, ["Vancouver", "Delta", "Burnaby"],
     "Richmond’s international community wants channels from home alongside Vancouver locals.", "", ["VANCOUVER"]),
    ("british-columbia", "Coquitlam", "coquitlam", VAN, ["Burnaby", "Vancouver", "Surrey"],
     "Coquitlam families get every Canucks game and Vancouver station.", "", ["VANCOUVER"]),
    ("british-columbia", "Abbotsford", "abbotsford", ["Abbotsford Canucks (AHL)"] + VAN[:1], ["Langley", "Surrey"],
     "Abbotsford has its own AHL team — the Canucks’ farm club.", "", ["VANCOUVER"]),
    ("british-columbia", "Kelowna", "kelowna", ["Kelowna Rockets (WHL)"] + VAN[:1], ["Kamloops", "Vancouver"],
     "Kelowna’s Okanagan lifestyle means plenty of summer outdoors — and Rockets hockey all winter.", "", ["VANCOUVER"]),
    ("british-columbia", "Victoria", "victoria", ["Victoria Royals (WHL)"] + VAN[:1], ["Nanaimo", "Vancouver"],
     "Victoria residents on Vancouver Island get all the Vancouver channels without crossing the water.", "", ["VANCOUVER"]),
    ("british-columbia", "Langley", "langley", ["Vancouver Giants (WHL)"] + VAN[:1], ["Surrey", "Abbotsford"],
     "Langley is home to the Vancouver Giants at the Langley Events Centre.", "", ["VANCOUVER"]),
    ("british-columbia", "Delta", "delta", VAN, ["Richmond", "Surrey", "Vancouver"],
     "Delta’s communities of Ladner, Tsawwassen and North Delta get the full Vancouver lineup.", "", ["VANCOUVER"]),
    ("british-columbia", "Nanaimo", "nanaimo", VAN, ["Victoria", "Vancouver"],
     "Nanaimo viewers follow the Canucks and BC Lions on Vancouver Island.", "", ["VANCOUVER"]),
    ("british-columbia", "Kamloops", "kamloops", ["Kamloops Blazers (WHL)"] + VAN[:1], ["Kelowna", "Vancouver"],
     "Kamloops is a proud WHL town — the Blazers have a long history.", "", ["VANCOUVER"]),
    # ------------------------------------------------------------- Alberta
    ("alberta", "Calgary", "calgary", CGY + ["Calgary Wranglers (AHL)", "Calgary Hitmen (WHL)"], ["Airdrie", "Red Deer", "Edmonton"],
     "Calgary households switched from cable in big numbers as prices rose. IPTV keeps the Flames, the Stampeders and Alberta news, and adds 50,000+ channels and a massive movie library.",
     "<h3>The Battle of Alberta</h3><p>Flames vs Oilers night? A 2-device plan lets a house divided watch on two TVs.</p>",
     ["CALGARY"]),
    ("alberta", "Edmonton", "edmonton", EDM + ["Edmonton Oil Kings (WHL)"], ["St. Albert", "Red Deer", "Calgary"],
     "Edmonton is one of the most searched cities for IPTV in Canada — and hockey is a big reason. Oilers fans want every game without paying for multiple sports add-ons.",
     "<h3>Watching the Oilers in 4K</h3><p>Use a 4K device (Firestick 4K Max, Nvidia Shield or Formuler) on a wired connection and pick the 4K sports feeds.</p>",
     ["CALGARY", "ALBERTA"]),
    ("alberta", "Red Deer", "red-deer", ["Red Deer Rebels (WHL)"] + CGY[:1] + EDM[:1], ["Calgary", "Edmonton"],
     "Red Deer sits between Calgary and Edmonton — and so do its fans.", "", ["CALGARY"]),
    ("alberta", "Lethbridge", "lethbridge", ["Lethbridge Hurricanes (WHL)"] + CGY[:1], ["Medicine Hat", "Calgary"],
     "Lethbridge viewers follow the Hurricanes and the Flames.", "", ["CALGARY"]),
    ("alberta", "St. Albert", "st-albert", EDM, ["Edmonton"],
     "St. Albert is Oilers country, just north of Edmonton.", "", ["ALBERTA"]),
    ("alberta", "Airdrie", "airdrie", CGY, ["Calgary", "Red Deer"],
     "Airdrie commuters get every Flames and Stampeders game.", "", ["CALGARY"]),
    ("alberta", "Medicine Hat", "medicine-hat", ["Medicine Hat Tigers (WHL)"] + CGY[:1], ["Lethbridge", "Calgary"],
     "Medicine Hat’s Tigers are a WHL institution.", "", ["CALGARY"]),
    ("alberta", "Fort McMurray", "fort-mcmurray", ["Fort McMurray Oil Barons (AJHL)"] + EDM[:1], ["Edmonton"],
     "Fort McMurray’s shift workers love catch-up TV that fits rotating schedules.", "", ["ALBERTA"]),
    # ------------------------------------------------------------- Prairies
    ("manitoba", "Winnipeg", "winnipeg", ["Winnipeg Jets (NHL)", "Winnipeg Blue Bombers (CFL)", "Manitoba Moose (AHL)"], ["Brandon", "Thunder Bay"],
     "Winnipeg sports fans are among the most loyal in the country, and IPTV lets them follow the Jets and Blue Bombers without a long cable contract.",
     "<h3>Cold-weather tip</h3><p>Winter storms rarely affect IPTV the way they can affect satellite dishes — as long as your internet is up, so is your TV.</p>",
     ["WINNIPEG", "MANITOBA"]),
    ("manitoba", "Brandon", "brandon", ["Brandon Wheat Kings (WHL)", "Winnipeg Jets (NHL)"], ["Winnipeg", "Regina"],
     "Brandon’s Wheat Kings are one of the WHL’s best-known teams.", "", ["MANITOBA"]),
    ("saskatchewan", "Saskatoon", "saskatoon", ["Saskatoon Blades (WHL)", "Saskatchewan Rush (NLL)", "Saskatchewan Roughriders (CFL)"], ["Regina"],
     "Saskatoon cheers the Riders, the Blades and the Rush — all on one IPTV subscription.", "", ["SASKATCHEWAN"]),
    ("saskatchewan", "Regina", "regina", ["Saskatchewan Roughriders (CFL)", "Regina Pats (WHL)"], ["Saskatoon", "Brandon"],
     "Regina is the home of Rider Nation — Mosaic Stadium game days are huge.", "", ["SASKATCHEWAN"]),
    # ------------------------------------------------------------- Atlantic
    ("nova-scotia", "Halifax", "halifax", ["Halifax Mooseheads (QMJHL)", "HFX Wanderers (CPL)", "Halifax Thunderbirds (NLL)"], ["Dartmouth", "Moncton", "Charlottetown"],
     "Halifax is an hour ahead of Eastern time, which makes late West Coast games very late. IPTV with catch-up and recording helps Maritimers watch on their own schedule.",
     "<h3>Atlantic time guide</h3><p>Set your IPTV app’s guide offset to Atlantic time so program times match your clock.</p>",
     ["HALIFAX"]),
    ("new-brunswick", "Moncton", "moncton", ["Moncton Wildcats (QMJHL)"], ["Saint John", "Fredericton", "Halifax"],
     "Moncton is bilingual — ICI Radio-Canada Moncton and Acadie channels are included alongside English networks.", "", ["MONCTON", "ACADIE"]),
    ("new-brunswick", "Saint John", "saint-john", ["Saint John Sea Dogs (QMJHL)"], ["Moncton", "Fredericton"],
     "Saint John’s Sea Dogs are a Memorial Cup-winning junior team.", "", ["ACADIE"]),
    ("new-brunswick", "Fredericton", "fredericton", ["Saint John Sea Dogs (QMJHL)", "Toronto Maple Leafs (NHL)"], ["Saint John", "Moncton"],
     "New Brunswick’s capital gets both English and French national networks.", "", ["ACADIE"]),
    ("newfoundland-and-labrador", "St. John’s", "st-johns", ["Toronto Maple Leafs (NHL)", "Montréal Canadiens (NHL)"], ["Halifax", "Charlottetown"],
     "St. John’s is on Newfoundland time — half an hour ahead of the Maritimes — so set your guide offset accordingly.", "", []),
    ("prince-edward-island", "Charlottetown", "charlottetown", ["Charlottetown Islanders (QMJHL)"], ["Moncton", "Halifax"],
     "Charlottetown viewers follow the Islanders and every national broadcast.", "", ["ACADIE"]),
]
